### ISSUE TITLE
Translating XYZ to TMS

### ISSUE THREAD

**Issue by zifix** [GeoWebCache/geowebcache#971] opened 2021-06-11 17:25 UTC
Hi,
I'm trying to convert from XYZ to TMS. 

Naturally I found out about shifting the Y coordinate, but I'm still confused why 0/0/0 gives me a partial view of the world, with 0/1/0 returning the other half.

For comparison https://tile.openstreetmap.de/0/0/0.png shows the whole planet.

Where am I thinking the wrong way? Or in other words, how would the following function look like correctly?

```
function xyz2tms(z, x, y) {
  return [ z, x, (1 << z) - 1 - y]
}
```

**Comment by zifix** [comment] 2021-06-12 08:57
I found a public GWC I can use to illustrate:
http://osm.franken.de:8080/geoserver/gwc/service/tms/1.0.0/gebco_2014/0/0/0.png

**Comment by groldan** [comment] 2024-01-05 07:50
Because that's how the EPSG:4326 griset is built. A webmercator one is square as you expect:
http://osm.franken.de:8080/geoserver/gwc/service/tms/1.0.0/gebco_2014@EPSG%3A900913@png/0/0/0.png

Closing as "not a bug".

**Closed by groldan** 2024-01-05 07:50 UTC
