### ISSUE TITLE
WMS Dimension not properly translated to WMTS

### ISSUE THREAD

**Issue by GatorScott** [GeoWebCache/geowebcache#520] opened 2017-06-12 20:14 UTC
WMTS capabilities document derived from WMS does not properly annotate the Identifier element of Dimension with ows, as in <ows:Identifier>FORECAST</ows:Identifier>.  This results in an invalid capabilities document.

**Comment by smithkm** [comment] 2017-11-25 00:05
By "derived from" do you mean you are using the WMS auto configuration?  Could you describe the steps to replicate more clearly?

**Comment by bossie** [comment] 2018-08-09 06:50
This is a duplicate of #679. :wink:

**Closed** 2018-08-09 20:41 UTC
Labels: Bug, Duplicate
