### ISSUE TITLE
TileLayer.getModifiableParameters() should not URLDecode strings from the input map

### ISSUE THREAD

**Issue by zeodtr** [GeoWebCache/geowebcache#377] opened 2016-03-15 01:05 UTC
org.geowebcache.layer.TileLayer.getModifiableParameters() calls ServletUtils.selectedStringsFromMap() to select relevant parameter strings from the map.

But the problem is ServletUtils.selectedStringsFromMap() URLDecode()s the map values, while the map's values have been already decoded.

This makes it impossible to include '%' character to the map values.

**Comment by smithkm** [comment] 2017-11-25 00:34
Duplicate of #193

**Closed by smithkm** 2017-11-25 00:34 UTC
Labels: Bug, Duplicate
